version: '3.3'

services:
  mysql:
    image: mysql:latest
    container_name: database
    ports:
      - "30330:3306"
    environment:
      MYSQL_ROOT_PASSWORD: R00t+
    volumes:
     - ./mysql/data.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - server_network
  
  mail_server:
    build: ./server/
    container_name: mail-server
    ports: 
      - "22222:22222"
    networks:
      - server_network


networks:
  server_network:
    driver: bridge
